### ISSUE TITLE
error with --> python caption.py 'YOUR_WORKING_PATH/'  'genSrt'

### ISSUE THREAD

**Issue by n0xi** [cgq5/Video-Caption#2]
Hello,

When i tried to **create the SRT** file, i have this error on my terminal :

octopus@octopus:~/MachineLearning/Video-Caption-with-Neuraltalk2$ **python caption.py '/home/octopus/MachineLearning/Video-Caption-with-Neuraltalk2/' 'genSrt'**
Traceback (most recent call last):
  File "caption.py", line 101, in <module>
    main()
  File "caption.py", line 97, in main
    srt_dict = parseOutput()
  File "caption.py", line 60, in parseOutput
    srt_dict[img_orig] = srt
**UnboundLocalError: local variable 'img_orig' referenced before assignment**

Any idea ? 

Ty, n0xi

**Comment by LiuDong777** [comment]
me too！Did you solve this problem?

**Comment by gqcao** [comment]
Did you generate the 'caplog.txt' correctly? If so, please remove the header and foot notes in the log, and leave only the caption information. It should work fine then.

**Comment by LiuDong777** [comment]
thanks!!! I have successfully solved the problem according to your suggestion.I am very  interested in the process of extracting key-frames, I want to know how to train the weights used in your models and how about the extraction mechanism , if I want to do some changes in my work  what should i do.I would be very  grateful for your reading!




------------------ 原始邮件 ------------------
发件人: "Guanqun Cao";<notifications@github.com>;
发送时间: 2017年8月24日(星期四) 下午3:40
收件人: "cgq5/Video-Caption-with-Neuraltalk2"<Video-Caption-with-Neuraltalk2@noreply.github.com>; 
抄送: "迷路的孩子"<1015696276@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [cgq5/Video-Caption-with-Neuraltalk2] error with --> pythoncaption.py 'YOUR_WORKING_PATH/' 'genSrt' (#2)




Did you generate the 'caplog.txt' correctly? If so, please remove the header and foot notes in the log, and leave only the caption information. It should work fine then.
